version: '3.1'

services:

  db-ilia-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABSE: ilia-ponto-eletronico
    volumes:
#      - ./volume:/var/lib/mysql
      - ./init/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge